[package]
name        = "effect-extras"
description = "An incubator for Flix effects"
version     = "0.5.0"
flix        = "0.76.1"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]


[mvn-dependencies]


