[package]
name        = "effect-extras"
description = "An incubator for Flix effects"
version     = "0.4.2"
flix        = "0.75.3"
license     = "Apache-2.0"
authors     = ["Stephen Tetley <stephen.tetley@gmail.com>"]

[dependencies]


[mvn-dependencies]


